### ISSUE TITLE
Skip preview for collections with one file

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#100]
If there is only one image in a collection, when one hits "Next" skip preview and go directly to the file
Skip the second screen here:
![IMG_0316](https://user-images.githubusercontent.com/2231711/57109289-eb28a500-6ce9-11e9-9d09-f6c4cadc0367.PNG)
![IMG_0317](https://user-images.githubusercontent.com/2231711/57109290-eb28a500-6ce9-11e9-9f96-4cc1831ddc93.PNG)
![IMG_0318](https://user-images.githubusercontent.com/2231711/57109291-ebc13b80-6ce9-11e9-9a76-420e72cecf0b.PNG)

**Comment by tladesignz** [comment]
Currently, not a good idea. If we do that, users can't upload, because the upload button is only on the preview list.

If you really want that, that would need an action sheet or a toolbar on this scene to select the next step. 

However, please note, that when there's more than one image in that colleciton and the user selects "upload" here, it is unclear, if the user wants to (or thinks it does) upload that one asset, or all of that collection. (Remember - you can swipe to the left and right to show the other images.)

This is actually related to #97.

**Comment by johnhess** [comment]
Closing per @tladesignz's comment.  Feel free to reopen w/ a response comment if this is something we indeed want to implement.
