### ISSUE TITLE
"No image available" on the preview screen comes when we take the picture directly from camera

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#158]
When we open the Save app and click a photo using camera for uploading, "No image available" is displayed on the Preview screen.

When we upload the same photo using camera roll or gallery, it is displayed correctly.

Save app version : 2.1.0(38)

Tested on iphone XR

Below is the screenshot  :

![no image available ](https://user-images.githubusercontent.com/8190141/63745124-0635ab00-c8bf-11e9-8012-5d980469d52e.jpg)

**Comment by tladesignz** [comment]
Neither could I just now on an iPhone 7.
When I take a photo in the image picker, it is added to the camera roll immediately and marked as selected. (And it shows a thumbnail.) Then when I add it, it also has a thumbnail.

I updated the image picker library just yesterday in my dev build, so am not sure, if that's why. On the other hand, @foundscapes has the same experience with the same build as you. Very strange.

I'll publish build 39 today. Please re-check with that and if problem persists, please paste screenshots of the image picker! Thanks!

Please also check, if your device is running out of storage!

**Comment by purvi-ranawat** [comment]
Issue no longer exist now.
