### ISSUE TITLE
make "enable nextcloud chunking" global setting / App Setting like in Android UI

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#169]
This is hard to find and is server-specific - we should map it to Android's UI to be in the "app settings" screen instead

**Comment by tladesignz** [comment]
As you said - it's server-specific. That's why I recommend against it and actually propose to change it in the Android version.

Consider the following case: A user has set up multiple WebDAV servers, one is a Nextcloud server, the other isn't. The app can't distinguish the difference. Having this as a global option makes the one server work, the other not. It will be very hard for the user to understand, why one works and the other not.

@n8fr8?

**Comment by foundscapes** [comment]
This makes total sense, @tladesignz - just trying to map Android features to iOS and thought it was cool to have it be so accessible, but since you can only use with nextcloud, we should absolutely change Android to match. Thank you!
