### ISSUE TITLE
Add ios app to f-droid

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#173]

**Comment by tladesignz** [comment]
AFAIK there's no F-Droid for iOS. There is Cydia for stuff which needs a jailbreak, but that seems to be slowly dying, as I can't even find up-to-date submission guides.

There's really not a huge demand for app stores outside Apple's one, since almost everybody has an Apple ID and can just use that.

There are some alternative installers, some of which don't need to have a jailbreak: https://cydia-app.com/alternative/

Please, decide for yourself, which ones we should support. Or better, yet: If this was a user request ask them, which app store they prefer.

**Comment by foundscapes** [comment]
hmm, that's a shame! Will do
