### ISSUE TITLE
Error while uploading is displayed if any phone call on mobile comes in between while uploading in Save app

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-ios#203]
Steps to Reproduce : 

1. Open Save App
2. Select few images and videos and click on Upload
3. Call on the phone on which the images and videos are being uploaded in Save App
4. Receive the phone call and talk for few mins
5. Return to the Save app after finishing the call

Expected Result :   
Upload of the images and videos should continue in the background when the phone call is received as the Save App is not closed

Actual Result :  
Error icon is displayed for the image which was being uploaded. Rest of the images and videos are uploaded successfully

Save App Version :  60

**Comment by johnhess** [comment]
@tladesignz I wonder if we should have an FAQ entry describing the limitations to uploading.  I suspect a good number of edge cases will be out of our control because of the OS or similar, and it'd be good to delineate "bad, but known" from "oh my, let's get that fixed".

If that's applicable here, do you want to put together a paragraph in the README?

**Comment by foundscapes** [comment]
@purvi-ranawat is this still an issue?

**Comment by purvi-ranawat** [comment]
@foundscapes This is working fine now.

Tested on below environment :
OS : IOS 17.2
Device : Iphone XR
Build version : 3.1.0, build 93
