### ISSUE TITLE
Login with Google button not working for IA setup flow

### ISSUE THREAD

**Issue by huertanix** [OpenArchive/Save-app-ios#208]
When going through the IA archive setup, creating a new API keypair brings up a webview with an IA login screen, which displays an "The Google library failed to load." error.

![save_ia_google_oauth_error](https://user-images.githubusercontent.com/72914/171096787-c3c1422f-1015-4757-9d7f-3ffe3033bd12.PNG)

When visiting the IA login screens from Safari outside of Save app, however, instead of seeing that error, I see the intended Log in with Google oauth button: https://archive.org/account/login.php

This may indicate that the internal webview may not be configured to be able to display the Google oauth button, maybe due to restrictions on JS, third-party cookies or something else along those lines.

**Comment by johnhess** [comment]
Thanks for documenting this one.  The error message is indeed an issue with Google's auth not working in a webview.

The approach we're planning on so far is a slightly broader scope: designing a better way for users to log into/upload to IA.  There's enough wrong with the current flow and enough in this particular issue we can't control that a more holistic approach seems justified.

**Comment by tladesignz** [comment]
Google denies login-with-Google inside webviews, because apps can inject their own JavaScript, which is needed and the whole point of webviews. 

Therefore, this is a systemic issue outside of our control we will never be able to do anything about.

The only other way I could think of is asking the user for their credentials and do the web requests ourselves. Which seems like an horrible idea.
