### ISSUE TITLE
IA Signup flow: Consider adding some sort of success messaging after generating new keys

### ISSUE THREAD

**Issue by huertanix** [OpenArchive/Save-app-ios#211]
In the final step of the IA signup flow, where keys are generated in the in-app webview and it's slid back to show the Access Key and Secret key page, it takes a second to realize that it worked, and may take longer for novice users. I would suggest maybe adding some sort of in-app success notification, and maybe some sort of "bounce in" type animation to show the fields went from empty to filled in a bit more viscerally; Similar to how some password managers use animation when filling in online forms.

**Comment by tladesignz** [comment]
Ok, I thought about this a little and did some experimenting:

1. Fancy animations can become very expensive quickly. What I can offer is a standard animation, where the table rows containing the key fields are replaced with fresh ones containing the keys with a swipe-in-from-[top|bottom|left|right] animation.
In theory. In practice, even that isn't easy to achieve, because what we're using here is a library which creates forms using `UITableViewControllers` and I have to find a way to make this work in conjunction with that library.
And even if I achieve that, I'm not sure, you're going to like that animation.
I understand where you're coming from, but please note that creating useful, sensible animations is a hard task, and while for apps like Facebook, where you can save 3 seconds times 1 billion users, this effort might be very worthwhile, it could become ridiculous over-engineering here  very quickly. (And we're not even talking accessibility...)
2. I don't just want to add a text alert as success message. The wording should be thought through and this will stand in the way and users don't even read it and are still confused (or even more so) after clicking it away.
3. Another solution would be to automatically trying to connect, after fetching the keys.

Since this scene is under heavy fire anyway(#209, #206), I'll rather wait for a full redesign.

**Comment by foundscapes** [comment]
Solved with Save 2.0 ux updates in #238 so closing this
