### ISSUE TITLE
Implement botton bar menu

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-ios#239]
The bottom bar menu has some new interactions:

![Home 2](https://github.com/OpenArchive/Save-app-android/assets/1177650/45641480-54d7-46e3-bcf7-df6c80ba4f47)

On the + button:

Single tap = native image gallery
Press and Hold = Bottom Menu selection to chose between photos and files browsing

![Bottom Menu](https://github.com/OpenArchive/Save-app-android/assets/1177650/f9f8d900-74b0-44ed-b243-399de4e7c0b1)

If you browse through photos you will see them all in grid:

![Single Tap - Select Image](https://github.com/OpenArchive/Save-app-android/assets/1177650/d4370450-518c-4f10-accd-6e95d2af0247)

If you browse through files you might see the contained folders:

![Folder](https://github.com/OpenArchive/Save-app-android/assets/1177650/d5984e95-4829-4eed-b0e6-bee4fe51d200)

Figma: 
https://www.figma.com/file/MngzLdtPsEmvEsUPKsbmE8/Save-App-2.0

**Comment by tladesignz** [comment]
This will be complete in version 3.0.0, build 82.

**Comment by purvi-ranawat** [comment]
@tladesignz : When we hold and press "+" icon, we get the options to select photos or files browsing. In this , when we click on files , we are not getting to see the folders available. Instead, we are able to see the photos only.

**Comment by tladesignz** [comment]
> @tladesignz : When we hold and press "+" icon, we get the options to select photos or files browsing. In this , when we click on files , we are not getting to see the folders available. Instead, we are able to see the photos only.

Not completely sure what you mean with that.

The file selector is completely provided by the OS. So there's not much we can do with it.

Do you use it in a simulator or a device which doesn't have an iCloud account connected? In that case, you won't see much, because iOS just doesn't have real local storage besides the camera roll. (There are apps which can hook in there, so you might be able to navigate to e.g. local Dropbox content, if you have that app installed and set up.)

Please provide a screenshot, in case you feel we're still talking past each other.

**Comment by vanichitkara** [comment]
@foundscapes For testing on iOS, I'll need an iPhone and I currently don't have one since I'm an android user.
