### ISSUE TITLE
Implement new general settings screen

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-ios#245]
New general settings are divided between:
- general
- space
- folder

![Dropbox-1](https://github.com/OpenArchive/Save-app-android/assets/1177650/98c8ad58-3ac2-4c9c-85fe-95e7a18b25fb)

The general settings screen contains options about the app itself:

![General](https://github.com/OpenArchive/Save-app-android/assets/1177650/454c351a-fe68-4ad6-ad66-70461383ec64)

There are two other panels that can be opened. For proofmode and media compression.

![ProofMode](https://github.com/OpenArchive/Save-app-android/assets/1177650/3303b25b-bf51-40f7-98fd-b28057420350)

![Compression](https://github.com/OpenArchive/Save-app-android/assets/1177650/da46f845-b696-4765-bf99-d738fa2bfa9d)

**Comment by tladesignz** [comment]
@purvi-ranawat, this will be contained in version 3.0.0, build 81.

**Comment by purvi-ranawat** [comment]
@tladesignz : Below is the mismatched of the content from the requirement screenshots and Actual screenshots : 

1. Below the  Folders, Disconnect from Dropbox is not displayed in actual screenshot. 



![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/d15310cd-cea0-4786-bf42-0a5c45f87d6d)

2. In General settings, Under Metadata> Proofmode Share ProofMode Public Key is not getting displayed (It gets displayed inside under Proof Mode screen)

3. In General settings, Under Security> Transfer Via Orbot only (content is different in the screenshot)



![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/1e75f0e3-14e8-4d0e-a1d7-b9ff6f145fc4)


4. In ProofMode Panel. the content is mismatched



![Image](https://github.com/OpenArchive/Save-app-ios/assets/8190141/2a468b41-4d46-498f-aea7-d1aec7ae771b)

**Comment by tladesignz** [comment]
> @tladesignz : Below is the mismatched of the content from the requirement screenshots and Actual screenshots :
> 
> 1. Below the  Folders, Disconnect from Dropbox is not displayed in actual screenshot.

And we neither implemented this on Android. 

I find this design inappropriate:  a text link  which looks the same and is on the same hierarchical level as some links to the website. But this one disconnects you.

There already is a button for that: You can disconnect a server inside the server's menu.

Needs to be discussed, if, how and why we want to improve the current situation, but this is definitely not the right way to do it.

> 2. In General settings, Under Metadata> Proofmode Share ProofMode Public Key is not getting displayed (It gets displayed inside under Proof Mode screen)

Yeah. That subtitle absolutely makes no sense there. Because there's way more levers inside there than sharing the key.

> 3. In General settings, Under Security> Transfer Via Orbot only (content is different in the screenshot)

On purpose. The uninformed blabla from the designer is outright dangerous. Tor has certain aspects, which improve your privacy and help you circumvent surveillance and (with additional tools) censorship, but it certainly doesn't "enable any advanced network security to protect my media". It can actually decrease (even physical personal!) security if used wrong, so we don't want to lure any uninformed users into things they don't understand.

> 4. In ProofMode Panel. the content is mismatched

Yep, I currently left it as-is. There's OS differences, there's more levers. In the design the subtitle actually needs to be the title of another lever. We need a final design here to finish this.

**Comment by foundscapes** [comment]
> > @tladesignz : Below is the mismatched of the content from the requirement screenshots and Actual screenshots :
> > 
> > 1. Below the  Folders, Disconnect from Dropbox is not displayed in actual screenshot.
> 
> And we neither implemented this on Android.

> 
> I find this design inappropriate: a text link which looks the same and is on the same hierarchical level as some links to the website. But this one disconnects you.

> 
> There already is a button for that: You can disconnect a server inside the server's menu.
> 
> Needs to be discussed, if, how and why we want to improve the current situation, but this is definitely not the right way to do it.

Yeah, not sure why this was in the designs, it doesn't make sense. Please disregard and close!

> 
> > 2. In General settings, Under Metadata> Proofmode Share ProofMode Public Key is not getting displayed (It gets displayed inside under Proof Mode screen)
> 
> Yeah. That subtitle absolutely makes no sense there. Because there's way more levers inside there than sharing the key.

agree
> 
> > 3. In General settings, Under Security> Transfer Via Orbot only (content is different in the screenshot)
> 
> On purpose. The uninformed blabla from the designer is outright dangerous. Tor has certain aspects, which improve your privacy and help you circumvent surveillance and (with additional tools) censorship, but it certainly doesn't "enable any advanced network security to protect my media". It can actually decrease (even physical personal!) security if used wrong, so we don't want to lure any uninformed users into things they don't understand.

yes, the most important ux feature for orbot/tor would be popups letting people know when/if connection drops if they change networks. The rest doesn't make sense.
> 
> > 4. In ProofMode Panel. the content is mismatched
> 
> Yep, I currently left it as-is. There's OS differences, there's more levers. In the design the subtitle actually needs to be the title of another lever. We need a final design here to finish this.

We need to have a longer discussion about Proofmode, will add to the calendar!

**Comment by tladesignz** [comment]
ProofMode changes to be continued in new issues.
