### ISSUE TITLE
Add Google Drive as a new backend 

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-ios#252]
I wish we could use Save to send media to Google Drive because many of our DACs would like to use it as a backend for their verified collections.

**Comment by tladesignz** [comment]
Ok. Support is there. Feels pretty solid for a first shot.

However, you @foundscapes, @ceylana need to jump through some Google hoops and get this personal inspection be done by Google. Because currently, when you first want to connect your Google account, it shows you a wiiiild warning which almost nobody will jump through.

This will be contained in build 93, available on TestFlight soon.

@uniqx, check out these commits/files if you still struggle with the Android implementation.

**Comment by purvi-ranawat** [comment]
@tladesignz I also got the warning from Google stating that it does not verify the app. I clicked on advance settings to connect to Google drive. 

Tested on iPhone XR. iOS 17.2, app version 3.1.0, build 93

**Comment by foundscapes** [comment]
![IMG_0427](https://github.com/OpenArchive/Save-app-ios/assets/2231711/6af4be98-6569-4b94-928e-044f3c6fcd7d)
@tladesignz is this the wiiiiiild error you mentioned? If so, it seems like we just need to have our dev admin (you!) finish verifying the app with google, no?

**Comment by tladesignz** [comment]
> Hi,
> 
> Thank you for your patience while we reviewed your project. 
> 
> Any use of Google user data obtained from Restricted and Sensitive Scopes must comply with the Limited Use Policy, and we suggest you disclose this to your users as described below. 
> 
> Next Steps
> 
> We recommend adding a disclosure that meets the following requirements:
> 
> 1. Easily visible to all users.
> 2. Under 500 characters.
> 3. Clearly calls out that the app complies with the Google API Services User Data Policy, including the Limited Use requirements.
> 4. Contains a link to the Google API Services User Data Policy so that it is easily accessible to all users.
> 
> Example disclosure: “(App’s) use and transfer of information received from Google APIs to any other app will adhere to Google API Services User Data Policy, including the Limited Use requirements.”
> 
> Note that apps distributed on Google Play are also subject to the Google Play Developer Distribution Agreement. 
> 
> Please reply directly to this email with the URL to the disclosure once it is added to your app or with confirmation that you will not be adding a disclosure. 
> 
> You can find more information in the Limited Use Requirements section of the OAuth API Verification FAQ. If you have questions, please answer this email directly.
> 
> Thanks,
> The Google Trust & Safety Security & Privacy Team

I suggest to add the requested text to either
a) on the second page of the connection wizard (the one which shows the Google Drive logo, the text "Google Drive" and the text "Sign in with Google." and shows the "Authenticate" button.
b) another screen in the wizard
c) a pop-up after tapping the "Authenticate" button.

I'd prefer (a), since that screen is quite empty, anyway.

Can you please provide a text which fulfils the requirements and may be shortly explains, that the needed access is only used to show the user their existing directories for them to select as an upload target. Nothing else happens with it. The app will forget about it immediately. no data exfiltration or anything else happens.


Or should we instead drop the "Browse Existing Folders" feature for the Google Drive support?

**Comment by ceylana** [comment]
@tladesignz  here is our language (let us know if it is okay and accurate). We also like option a (regarding where the text is placed)

**_Save’s_** use and transfer of information received from Google APIs to any other app adheres to [Google API Services User Data Policy](https://developers.google.com/terms/api-services-user-data-policy), including the Limited Use requirements.

Google’s APIs allow you to access and send media to your existing folders in Google Drive via  **_Save_**. Although Google will store and see your data sent via **_Save_**, **_Save_** never has access to your data.

**Comment by foundscapes** [comment]
More concise/clear - how's this? @tladesignz @ceylana 

Save’s use and transfer of information received from Google APIs to any other app adheres to [Google API Services User Data Policy](https://developers.google.com/terms/api-services-user-data-policy), including the Limited Use requirements.

Google's APIs allow you to access and send media to your existing folders in Google Drive via Save. Although Google will store and see your data sent via Save and Save will be able to see your GDrive folders if/when you select from existing folders, Save does not store that information, which is removed immediately after selecting a folder.

Save will only read the list of folders from your Google Drive for the sole purpose of showing it to you so you can select one. This information is immediately forgotten afterwards.

**Comment by tladesignz** [comment]
> @tladesignz deleted? what is a more technically accurate word than "forgotten"?

In my opinion "forgotten" was just right, because that information is never stored anywhere. It only resides in RAM. When the user leaves the scene, the used memory is freed. This is how computers actually "forget".

But I don't really want to argue about that word. This was just FYI.

I'm fine with whatever text you provide, as long as it is not such, that I expect the Google inspector will throw it back at us.

So I'll just take your last suggestion, that seems good enough.

**Comment by tladesignz** [comment]
This will be contained in build 105. 

I already sent a new video for the Google verification process.
