### ISSUE TITLE
After selecting media to upload can we add an edit metadata button 

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#257]
**Describe the bug**
Right now when we select media to upload, you tap the media to add the metadata. Can we add a button on the bottom left to do that also in case people forget that you have to tap the photo again to edit the metadata before upload 

**To Reproduce**
1. Go to plus icon and select media to upload 
2. Click on 'done
4. See error (no edit metadata button) 

**Expected behavior**
Might be more intuitive to add a edit metadata icon in case people forget that they need to tap the photo and add metadata before upload. 

**Smartphone (please complete the following information):**
 - Device: iphone 12 mini
 - OS:  17.1.1
 - Version 3.0.0 85

**Comment by ceylana** [comment]
@tladesignz tabling management response on this until January because this was a comment Natalie had and since it involves both versions and a change to the designs I want to discuss with her. Also doesn't impact the use of the app now.

**Comment by foundscapes** [comment]
Ok so all we really need to do to solve this issue is to have the multi-edit icon appear after selecting media for upload
![signal-2024-01-02-122203_002](https://github.com/OpenArchive/Save-app-ios/assets/2231711/52c3fae0-cca1-4e93-acb9-bc7e0ce9ba4d)
![signal-2024-01-02-122203_003](https://github.com/OpenArchive/Save-app-ios/assets/2231711/20b87cff-611a-4c65-b5df-0e0cda355b9f)

**Comment by tladesignz** [comment]
Will be contained in build 94.

**Comment by purvi-ranawat** [comment]
This is working fine.

Environment Details : 

OS : IOS 17.2
Device : Iphone XR
Build version : 3.0.0, build 100
