### ISSUE TITLE
Upload Progress % Missing

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#259]
**Describe the bug**
When media is uploading we no longer see the % uploaded which we would like to see

**Screenshots**

**Smartphone (please complete the following information):**
 - Device:  iphone 12 mini
 - OS: 17.1.1
 - Version 3.0.0 85
![percentage](https://github.com/OpenArchive/Save-app-ios/assets/145493085/909ae634-a74b-4402-8709-e23855fce002)

**Comment by ceylana** [comment]
@tladesignz thanks for outlining what it would take to replace the lib. 

I think we definitely want the percentage to show up somewhere but yea, you are right and it wasn't in the figma designs. We can likely deprioritize this for now.

One issue/discrepancy between the UI designs and current app is the the width of the circle and overlay on the image when it is uploading. Right now it is difficult to see the upload circle because it is thin and there is a white overlay on the images. Can we increase the width of the teal upload circle and change the photo overlay to a transparent black like this 
![image](https://github.com/OpenArchive/Save-app-ios/assets/37166640/82e6e1d0-c9bf-4809-9864-3ac315e854b0)

Would that also require replacing the lib?

**Comment by ceylana** [comment]
@tladesignz so we definitely need to replace the lib in some way because as it is now it is to difficult to see (and likely won't pass accessibility standards). Let's move forward with replacing the library, it is a crucial part of the app functionality (seeing upload progress) so worth the time

**Comment by tladesignz** [comment]
Will be contained in version 3.0.1, build 91.

**Comment by losalim** [comment]
Thank you @tladesignz confirming that the upload progress tracker is thicker as requested. I know the % requires more work/replacing of the library which Alex has indicated we would like to move forward with. Do we know how far out that is?

**Comment by losalim** [comment]
Hi @tladesignz I'm on build 91. Attached a screen recording here. The circle is now thicker like Alex recommended, but i didn't see a percent sorry! But now that i re-watch it i'm thinking it's the 3 that i see briefly in the edit window. 

https://github.com/OpenArchive/Save-app-ios/assets/145493085/3af4e228-71d8-421e-8e26-dbebc0c4d135

**Comment by losalim** [comment]
Tested with a larger upload and i can, in fact, see the percent. Thank you!

**Comment by foundscapes** [comment]
@tladesignz This is not working for me - iphone 12 mini - ios 17.1.2
See attached video, their is neither a status circle in gallery view, nor numbers with % signs in the circle in edit view (altho some numbers do show up). The biggest issue is that there is no accurate progress / status because files showing as uploaded when toggling back to gallery scene from edit scene, but say only "2" on edit scene or just go back to the upload arrow in circle - see video:


https://github.com/OpenArchive/Save-app-ios/assets/2231711/f0c9b028-6205-4be7-9454-6ccde859bddb

**Comment by tladesignz** [comment]
Good catch! Seems I used the wrong `uploadProgressBlock` method to catch the progress. The first one I found actually didn't do anything.

Fix will be contained in build 98.

**Comment by foundscapes** [comment]
Now we have numbers in circles on edit scene, but no %, neither numbers nor % are showing up in circle on gallery scene and the app continually crashed repeatedly when I was in edit mode and trying to reorder the video to go last after one photo - ios: 17.1.2 iphone 12 mini, server: nextcloud, uploading two photos and one video, see video (too big to upload here): https://share.icloud.com/photos/0a59c6jF9-0_Z_Myxc-KA-3LA 

Lauren did not have it crash when doing the same thing on DropBox - she is on iphone 12 mini ios: 17.1.1

**Comment by tladesignz** [comment]
I didn't add the "%" symbol, as that makes the numbers barely readable, because everything needs to become so small, when we add another character.

The numbers show up once in a while, but when the files are small and the connection fast, you might end up seeing nothing. We depend on the OS resp. other libraries calling us back with a progress here. If that doesn't happen, we can't do anything about it.

For the future, when crashes happen:
Please use the TestFlight versions and send a crash report. (It should ask you if you want to do that, after the app crashed.)
I can then pick up a stack trace which helps me identify the problem via AppStoreConnect.

I'll try to reproduce now, but can't promise anything.

**Comment by tladesignz** [comment]
Fix for crashes will be contained in build 99.

**Comment by foundscapes** [comment]
@tladesignz will do re: crashes (it did not ask me to send crash report when it crashed but it was in build 98. 

I get why there isn't room anymore for a % (there used to be, so I'm not sure why things got so small?), however, we do need the number in the circle at least on the gallery scene, and it's not there. Please add.

**Comment by tladesignz** [comment]
Good catch, @purvi-ranawat!

A fix will be contained in build 104.

**Comment by purvi-ranawat** [comment]
This is working fine.

Environment : 

OS : IOS 17.2
Device : Iphone XR
Build Version : 3.2.1, build 109
