### ISSUE TITLE
Font in iOS is incorrect

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-ios#263]
**Describe the bug**
Font throughout app should be Montserrat

**Smartphone (please complete the following information):**
 - Device: iphone 12 mini
 - OS: 17.1.1
 - Version 3.0.1. build 90

**Comment by tladesignz** [comment]
Unfortunately, this isn't a just-fix-once-and-be-good issue.

Can you please show me, where it is wrong? I'm afraid I will have to take care of every single item personally.

**Comment by tladesignz** [comment]
Ahahaha. I played around with this problem. Again. And now, I remember:

It is ridiculously complicated to replace the font everywhere, hence we agreed on only using Montserrat in headings and such. Many of these probably didn't survive the redesign, because I forgot about it.

Anyway, I tried to fulfil your wish, and I probably succeeded mostly.

Go hunt for missing changes. Could be, that we cannot do anything about it without spending horrendous amounts of hours on it, but eventually, you'll find some, which are easy to fix.

That font still looks ugly on iOS, from my point of view. But, well, you're paying, so there you are.

**Comment by tladesignz** [comment]
Will be contained in version 3.0.1, build 91, which I'll upload in a minute!

**Comment by losalim** [comment]
I agree i think this is largely fixed. one issue though is that the first welcome screen that says SAVE down the side now also has that font when i think that page was supposed to be unique

**Comment by tladesignz** [comment]
> I agree i think this is largely fixed. one issue though is that the first welcome screen that says SAVE down the side now also has that font when i think that page was supposed to be unique

That's one of the obstacles, why it makes it difficult to change a font app-wide.

I fixed it for that special case. Will be contained in build 92.

Let me know, if you find more of these places, @losalim.

**Comment by losalim** [comment]
Tested on build 93. All fixed thank you!
